openapi: 3.0.0
info:
  title: Rider API
  version: 1.0.0
paths:
  /rider:
    get:
      summary: Retrieve a list of riders
      responses:
        200:
          description: A list of riders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: object
                      properties:
                        first:
                          type: string
                        last:
                          type: string
